export const DataTreinador = [
    {
        time: "Corinthians/SP - 2002",
        trabalho: "Estágio com Carlos Alberto Parreira",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"",
        Vitorias:"",
        Empates:"",
        Derrotas:"",
        Aproveitamento:"",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1622769279/image_101_6_tsig2q.png",
        Amistosos: "",
    },
    {
        time: "Grêmio/RS - 2003",
        trabalho: "Auxiliar Técnico do Dario Pereira",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"",
        Vitorias:"",
        Empates:"",
        Derrotas:"",
        Aproveitamento:"",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040843/Gremio-Logo_qvk2m8.png",
        Amistosos: "",
    },
{
        time: "Vila Nova/MG - 2003/2004",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J20-",
        Vitorias:"V9-",
        Empates:"E6-",
        Derrotas:"D5",
        Aproveitamento:"55%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/villa_nova_sedqwf.png",
        Amistosos: "",
    },
    {
        time: "Santos/SP - 2004",
        trabalho: "Auxiliar Técnico do Wanderley Luxembugo",
        Trofeu1: "Campeonato Brasileiro (Campeão)",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J20-",
        Vitorias:"V9-",
        Empates:"E6-",
        Derrotas:"D5",
        Aproveitamento:"",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040844/LogoSantosFC_zobpvy.png",
        Amistosos: "",
    },
    {
        time: "Portuguesa/SP - 2005",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J7-",
        Vitorias:"V3-",
        Empates:"E2-",
        Derrotas:"D2",
        Aproveitamento:"52,83%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1622765695/image_65_2_t8zwue.png",
        Amistosos: "",
    },
    {
        time: "Santos/SP - 2005",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J42-",
        Vitorias:"V20-",
        Empates:"E11-",
        Derrotas:"D11",
        Aproveitamento:"56,34%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040844/LogoSantosFC_zobpvy.png",
        Amistosos: "",
    },
    {
        time: "FC Tokyo (Japão) - 2006",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J28-",
        Vitorias:"V13-",
        Empates:"E7-",
        Derrotas:"D8",
        Aproveitamento:"54,76%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/fctokyo_xqb80c.png",
        Amistosos: "Inclui Jogos amistosos",
    },
    {
        time: "Sport Clube Recife/PE - 2007",
        trabalho: "Treinador",
        Trofeu1: "Campeonato Pernambucano (Campeão)",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J28-",
        Vitorias:"V22-",
        Empates:"E5-",
        Derrotas:"D1",
        Aproveitamento:"84,52%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040843/sport_zdmvsa.png",
        Amistosos: "",
    },
    {
        time: "Internacional/RS - 2007",
        trabalho: "Treinador",
        Trofeu1: "Recopa SulAmericana (Campeão)",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J21-",
        Vitorias:"V9-",
        Empates:"E3-",
        Derrotas:"D9",
        Aproveitamento:"47,61%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040843/internacional_wynpb4.png",
        Amistosos: "",
    },
    {
        time: "Figueirense/SC - 2007/2008",
        trabalho: "Treinador",
        Trofeu1: "Campeonato Catarinense (Campeão)",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J40-",
        Vitorias:"V23-",
        Empates:"E9-",
        Derrotas:"D8",
        Aproveitamento:"65%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/figueirense_ln5nfa.png",
        Amistosos: "",
    },
    {
        time: "Atlético-MG/MG - 2008",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J14-",
        Vitorias:"V4-",
        Empates:"E4-",
        Derrotas:"D6",
        Aproveitamento:"38,09%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1622766767/image_100_apllnq.png",
        Amistosos: "",
    },
    {
        time: "Bahia-BA - 2009",
        trabalho: "Treinador",
        Trofeu1: "Campeonato Baiano (Vice-Campeão)",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J39-",
        Vitorias:"V21-",
        Empates:"E10-",
        Derrotas:"D8",
        Aproveitamento:"55%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/bahia_ox5zgp.png",
        Amistosos: "",
    },
    {
        time: "Náutico/PE - 2010",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J44-",
        Vitorias:"V21-",
        Empates:"E8-",
        Derrotas:"D15",
        Aproveitamento:"53, 79% ",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040845/Simbolo-escudo-nautico_uzsuel.png",
        Amistosos: "",
    },
    {
        time: "Al Ain Football club - 2011",
        trabalho: "Treinador",
        Trofeu1: "Vice Campeão da Etisalat Emirates Cup (2011)",
        Trofeu2: "Campeão da Arabian Gulf Reserve League (2011)",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J38-",
        Vitorias:"V19-",
        Empates:"E9-",
        Derrotas:"D10",
        Aproveitamento:"57,89%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/alain_xvsbtk.png",
        Amistosos: "Inclui Jogos amistosos",
    },
    {
        time: "Avai/SC - 2011",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J13-",
        Vitorias:"V3-",
        Empates:"E3-",
        Derrotas:"D7",
        Aproveitamento:"30,76%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/Avai_FC__05-E__-_SC.svg_dgonre.png",
        Amistosos: "",
    },
    {
        time: "Náutico/PE - 2012",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J43-",
        Vitorias:"V16-",
        Empates:"E9-",
        Derrotas:"D18",
        Aproveitamento:"44,18%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040845/Simbolo-escudo-nautico_uzsuel.png",
        Amistosos: "",
    },
    {
        time: "Seleção Brasileira Sub-15 - 2013",
        trabalho: "Treinador",
        Trofeu1: "Torneio Internacional de Salt (Campeão)",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J3-",
        Vitorias:"V1-",
        Empates:"E1-",
        Derrotas:"D1",
        Aproveitamento:"44,44%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1622765999/image_66_pwe5xo.png",
        Amistosos: "",
    },
    {
        time: "Seleção Brasileira Sub-17 - 2013/2014",
        trabalho: "Treinador",
        Trofeu1: "Copa 2 de Julho (Campeão)",
        Trofeu2: "Taça Centenário do Clube Atlético Carlos Renaux (Campeão)",
        Trofeu3: "Torneio de Banyoles (campeão)",
        Trofeu4: "",
        Jogos:"J18-",
        Vitorias:"V12-",
        Empates:"E6-",
        Derrotas:"D0",
        Aproveitamento:"77,77%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1622765999/image_66_pwe5xo.png",
        Amistosos: "",
    },
    {
        time: "Seleção Brasileira Sub-20 - 2013/2014",
        trabalho: "Treinador",
        Trofeu1: "Toreneio de Toulon (Campeão)",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J22-",
        Vitorias:"V14-",
        Empates:"E4-",
        Derrotas:"D4",
        Aproveitamento:"69,69%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1622765999/image_66_pwe5xo.png",
        Amistosos: "",
    },
    {
        time: "Seleção Brasileira Olímpica - 2013/2014",
        trabalho: "Treinador",
        Trofeu1: "Torneio de Toulon (Bi campeão)",
        Trofeu2: "Valais Youth Cup (Campeão)", 
        Trofeu3: "Panda Cup (Campeão)", 
        Trofeu4: "Torneio de COTIF Espanha (Campeão)",
        Jogos:"J31-",
        Vitorias:"V24-",
        Empates:"E7-",
        Derrotas:"D0",
        Aproveitamento:"84,94%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1622765999/image_66_pwe5xo.png",
        Amistosos: "",
    },
    {
        time: "Al-Qadisyah khubar - 2015/2016",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J14-",
        Vitorias:"V3-",
        Empates:"E5-",
        Derrotas:"D6",
        Aproveitamento:"33,33%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/alqadisiyah_xsg9zz.png",
        Amistosos: "Inclui Jogos Amsitostos"
    },
    {
        time: "Ponte Preta/SP - 2016",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J12-",
        Vitorias:"V7-",
        Empates:"E2-",
        Derrotas:"D3",
        Aproveitamento:"63,88%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040844/pontepreta_qqy0ix.png",
        Amistosos: "",
    },
    {
        time: "Náutico/PE - 2016",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J26-",
        Vitorias:"V12-",
        Empates:"E4-",
        Derrotas:"D10",
        Aproveitamento:"51,28%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040845/Simbolo-escudo-nautico_uzsuel.png",
        Amistosos: "",
    },
    {
        time: "Vitória/BA - 2017",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J11-",
        Vitorias:"V3-",
        Empates:"E2-",
        Derrotas:"D6",
        Aproveitamento:"44,18%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/Vit%C3%B3ria_qq0sz4.png",
        Amistosos: "",
    },
    {
        time: "Atlético-MG/MG - 2018",
        trabalho: "Diretor",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"J58-",
        Vitorias:"V25-",
        Empates:"E15-",
        Derrotas:"D18",
        Aproveitamento:"51,72%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/1200px-Atletico_mineiro_galo_ly6lgh.png",
        Amistosos: "",
    },
    {
        time: "São Caetano/SP - 2020",
        trabalho: "Treinador",
        Trofeu1: "Acesso a Série A1 do Campeonato Paulista (2020)",
        Trofeu2: "Campeão da Série A2 do Campeonato Paulista (2020)",
        Trofeu3:"",
        Trofeu4:"",
        Jogos:"J22-",
        Vitorias:"V12-",
        Empates:"E4-",
        Derrotas:"D6",
        Aproveitamento:"60,60%",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/saocaetano_a5acmy.png",
        Amistosos: "",
    },
    {
        time: "Botafogo de Ribeirão Preto/SP - 2021",
        trabalho: "Treinador",
        Trofeu1: "",
        Trofeu2: "",
        Trofeu3: "",
        Trofeu4: "",
        Jogos:"",
        Vitorias:"",
        Empates:"",
        Derrotas:"",
        Aproveitamento:"",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/BotafogoFCRB_szwvxw.png",
        Amistosos: "",
    },
    
]

    