export const dataTreinador = [
    {
        time: "Corinthians/SP",
        ano: "2002",
        trabalho: "Estágio com Carlos Alberto Parreira",
        Trofeu: "",
        Jogos:"",
        Vitorias:"",
        Empates:"",
        Derrotas:"",
        Aproveitamento:"",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/corinthians_adfphu.png",
        Amistosos: "",
    },
    {
        time: "Grêmio/RS",
        ano: "2003",
        trabalho: "Auxiliar Técnico do Dario Pereira",
        Trofeu: "",
        Jogos:"",
        Vitorias:"",
        Empates:"",
        Derrotas:"",
        Aproveitamento:"",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040843/Gremio-Logo_qvk2m8.png",
        Amistosos: "",
    },
{
        time: "Vila Nova/MG",
        ano: "2003/2004",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J20",
        Vitorias:"V9",
        Empates:"E6",
        Derrotas:"D5",
        Aproveitamento:"55%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/villa_nova_sedqwf.png",
        Amistosos: "",
    },
    {
        time: "Santos/SP",
        ano: "2004",
        trabalho: "Auxiliar Técnico do Wanderley Luxembugo",
        Trofeu: "Campeonato Brasileiro (Campeão)",
        Jogos:"J20",
        Vitorias:"V9",
        Empates:"E6",
        Derrotas:"D5",
        Aproveitamento:"",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040844/LogoSantosFC_zobpvy.png",
        Amistosos: "",
    },
    {
        time: "Portuguesa/SP",
        ano: "2005",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J7",
        Vitorias:"V3",
        Empates:"E2",
        Derrotas:"D2",
        Aproveitamento:"52,83%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040844/Portuguesa_e5p2r5.png",
        Amistosos: "",
    },
    {
        time: "Santos/SP",
        ano: "2005",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J42",
        Vitorias:"V20",
        Empates:"E11",
        Derrotas:"D11",
        Aproveitamento:"56,34%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040844/LogoSantosFC_zobpvy.png",
        Amistosos: "",
    },
    {
        time: "FC Tokyo (Japão)",
        ano: "2006",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J28",
        Vitorias:"V13",
        Empates:"E7",
        Derrotas:"D8",
        Aproveitamento:"54,76%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/fctokyo_xqb80c.png",
        Amistosos: "Inclui Jogos amistosos",
    },
    {
        time: "Sport Clube Recife/PE",
        ano: "2007",
        trabalho: "Treinador",
        Trofeu: "Campeonato Pernambucano (Campeão)",
        Jogos:"J28",
        Vitorias:"V22",
        Empates:"E5",
        Derrotas:"D1",
        Aproveitamento:"84,52%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040843/sport_zdmvsa.png",
        Amistosos: "",
    },
    {
        time: "Internacional/RS",
        ano: "2007",
        trabalho: "Treinador",
        Trofeu: "Recopa SulAmericana (Campeão)",
        Jogos:"J21",
        Vitorias:"V9",
        Empates:"E3",
        Derrotas:"D9",
        Aproveitamento:"47,61%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040843/internacional_wynpb4.png",
        Amistosos: "",
    },
    {
        time: "Figueirense/SC",
        ano: "2007/2008",
        trabalho: "Treinador",
        Trofeu: "Campeonato Catarinense (Campeão)",
        Jogos:"J40",
        Vitorias:"V23",
        Empates:"E9",
        Derrotas:"D8",
        Aproveitamento:"65%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/figueirense_ln5nfa.png",
        Amistosos: "",
    },
    {
        time: "Atlético-MG/MG",
        ano: "2008",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J14",
        Vitorias:"V4",
        Empates:"E4",
        Derrotas:"D6",
        Aproveitamento:"38,09%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/1200px-Atletico_mineiro_galo_ly6lgh.png",
        Amistosos: "",
    },
    {
        time: "Bahia-BA",
        ano: "2009",
        trabalho: "Treinador",
        Trofeu: "Campeonato Baiano (Vice-Campeão)",
        Jogos:"J39",
        Vitorias:"V21",
        Empates:"E10",
        Derrotas:"D8",
        Aproveitamento:"55%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/bahia_ox5zgp.png",
        Amistosos: "",
    },
    {
        time: "Náutico/PE",
        ano: "20010/2012 e 2016",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J44",
        Vitorias:"V21",
        Empates:"E8",
        Derrotas:"D15",
        Aproveitamento:"53,79%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040845/Simbolo-escudo-nautico_uzsuel.png",
        Amistosos: "",
    },
    {
        time: "Al Ain Football club",
        ano: "2011",
        trabalho: "Treinador",
        Trofeu: ["Vice Campeão da Etisalat Emirates Cup (2011)",
        "Campeão da Arabian Gulf Reserve League (2011)"],
        Jogos:"J38",
        Vitorias:"V19",
        Empates:"E9",
        Derrotas:"D10",
        Aproveitamento:"57,89%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/alain_xvsbtk.png",
        Amistosos: "Inclui Jogos amistosos",
    },
    {
        time: "Avai/SC",
        ano: "2011",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J13",
        Vitorias:"V3",
        Empates:"E3",
        Derrotas:"D7",
        Aproveitamento:"30,76%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/Avai_FC__05-E__-_SC.svg_dgonre.png",
        Amistosos: "",
    },
    {
        time: "Náutico/PE",
        ano: "2012",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J43",
        Vitorias:"V16",
        Empates:"E9",
        Derrotas:"D18",
        Aproveitamento:"44,18%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040845/Simbolo-escudo-nautico_uzsuel.png",
        Amistosos: "",
    },
    {
        time: "Seleção Brasileira Sub-15",
        ano: "2013",
        trabalho: "Treinador",
        Trofeu: "Torneio Internacional de Salt (Campeão)",
        Jogos:"J3",
        Vitorias:"V1",
        Empates:"E1",
        Derrotas:"D1",
        Aproveitamento:"44,44%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/Brasil_CBF_bui16p.png",
        Amistosos: "",
    },
    {
        time: "Seleção Brasileira Sub-17",
        ano: "2013/2014",
        trabalho: "Treinador",
        Trofeu: ["Copa 2 de Julho (Campeão)",
                "Taça Centenário do Clube Atlético Carlos Renaux (Campeão)",
                "Torneio de Banyoles (campeão)"],
        Jogos:"J18",
        Vitorias:"V12",
        Empates:"E6",
        Derrotas:"D0",
        Aproveitamento:"77,77%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/Brasil_CBF_bui16p.png",
        Amistosos: "",
    },
    {
        time: "Seleção Brasileira Sub-20",
        ano: "2013/2014",
        trabalho: "Treinador",
        Trofeu: "Toreneio de Toulon (Campeão)",
        Jogos:"J22",
        Vitorias:"V14",
        Empates:"E4",
        Derrotas:"D4",
        Aproveitamento:"69,69%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/Brasil_CBF_bui16p.png",
        Amistosos: "",
    },
    {
        time: "Seleção Brasileira Olímpica",
        ano: "2013/2014",
        trabalho: "Treinador",
        Trofeu: ["Torneio de Toulon (Bi campeão)",
        "Valais Youth Cup (Campeão)", 
        "Panda Cup (Campeão)", 
        "Torneio de COTIF Espanha (Campeão)"],
        Jogos:"J31",
        Vitorias:"V24",
        Empates:"E7",
        Derrotas:"D0",
        Aproveitamento:"84,94%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/Brasil_CBF_bui16p.png",
        Amistosos: "",
    },
    {
        time: "Al-Qadisyah khubar",
        ano: "2015/2016",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J14",
        Vitorias:"V3",
        Empates:"E5",
        Derrotas:"D6",
        Aproveitamento:"33,33%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/alqadisiyah_xsg9zz.png",
        Amistosos: "Inclui Jogos Amsitostos"
    },
    {
        time: "Ponte Preta/SP",
        ano: "2016",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J12",
        Vitorias:"V7",
        Empates:"E2",
        Derrotas:"D3",
        Aproveitamento:"63,88%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040844/pontepreta_qqy0ix.png",
        Amistosos: "",
    },
    {
        time: "Náutico/PE",
        ano: "2016",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J26",
        Vitorias:"V12",
        Empates:"E4",
        Derrotas:"D10",
        Aproveitamento:"51,28%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040845/Simbolo-escudo-nautico_uzsuel.png",
        Amistosos: "",
    },
    {
        time: "Vitória/BA",
        ano: "2017",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"J11",
        Vitorias:"V3",
        Empates:"E2",
        Derrotas:"D6",
        Aproveitamento:"44,18%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/Vit%C3%B3ria_qq0sz4.png",
        Amistosos: "",
    },
    {
        time: "Atlético-MG/MG",
        ano: "2018",
        trabalho: "Diretor",
        Trofeu: "",
        Jogos:"J58",
        Vitorias:"V25",
        Empates:"E15",
        Derrotas:"D18",
        Aproveitamento:"51,72%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/1200px-Atletico_mineiro_galo_ly6lgh.png",
        Amistosos: "",
    },
    {
        time: "São Caetano/SP",
        ano: "2020",
        trabalho: "Treinador",
        Trofeu: ["Acesso a Série A1 do Campeonato Paulista (2020)",
        "Campeão da Série A2 do Campeonato Paulista (2020)"],
        Jogos:"J22",
        Vitorias:"V12",
        Empates:"E4",
        Derrotas:"D6",
        Aproveitamento:"60,60%Aproveitamento",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040841/saocaetano_a5acmy.png",
        Amistosos: "",
    },
    {
        time: "Botafogo de Ribeirão Preto/SP",
        ano: "2021",
        trabalho: "Treinador",
        Trofeu: "",
        Jogos:"",
        Vitorias:"",
        Empates:"",
        Derrotas:"",
        Aproveitamento:"",
        Escudo: "https://res.cloudinary.com/gallo/image/upload/v1617040842/BotafogoFCRB_szwvxw.png",
        Amistosos: "",
    },
]

    